# dict = {"a":[1, 2, 3], "b":4}
# print(dict)
# keys = dict.keys()
# print("keys\n")
# print(type(keys))
# print(keys)
# keys = list(keys)
# print(type(keys))
# print(keys)
# dict.pop("b")
# print(dict)
my_iter = iter([1, 2])
print(next(my_iter))
print(next(my_iter))
print(type(my_iter))

print(type(iter(range(5))))
